### ISSUE TITLE
does not work with Flint 2.6.0

### ISSUE THREAD

**Issue by dimpase** [videlec/e-antic#93]
There are at least 2 issues here:

* configure switch `--enable-flint-devel` still does not allow to build with newer than 2.5.2 flint, giving
```
[e_antic-0.1.5] In file included from ./e-antic/poly_extra.h:15,
[e_antic-0.1.5]                  from poly_extra/bisection_step_arb.c:12:
[e_antic-0.1.5] ./e-antic/e-antic.h:24:2: error: #error FLINT 2.5.2 or 2.5.3 required
[e_antic-0.1.5]  #error FLINT 2.5.2 or 2.5.3 required
[e_antic-0.1.5]   ^~~~~
```
* further breakage, see https://trac.sagemath.org/ticket/29719 (note an arb patch we apply there, maybe that's the same thing?)

**Comment by videlec** [comment]
In progress at https://github.com/videlec/e-antic/pull/94

**Comment by videlec** [comment]
(will be backported to `master0` afterwards)

**Comment by videlec** [comment]
requires https://github.com/wbhart/flint2/pull/766

**Comment by dimpase** [comment]
good catch!

**Comment by videlec** [comment]
fixed in master and master0
